version: 2
jobs:
  build-python-3.6:
    docker:
    - image: circleci/python:3.6.7-stretch-node-browsers
    working_directory: ~/project
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.05.0-ce
    - run: sudo apt-get update && sudo apt-get install git git-crypt awscli zip -y
    - run: sudo pip install -U pip
    - run: .circleci/gpgsetup.sh
    - run: |
          export PROJECT_FOLDER=platform-services/analysis-service
          cd $PROJECT_FOLDER
          npm install --silent
          npm run deploy


workflows:
  version: 2
  build:
    jobs:
    - build-python-3.6:
        context: serverless
        filters:
          branches:
            only:
            - master