[package]
name = "spacemaker-course-example-rust"
version = "0.1.0"
authors = ["Håvard Wormdal Høiby <havardwhoiby@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
iron = "*"
