---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spacemaker-python-flask-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: spacemaker-python-flask-pod
  template:
    metadata:
      labels:
        app: spacemaker-python-flask-pod
    spec:
      containers:
      - name: spacemaker-python-flask-container
        image: hakonamdal/spacemaker-python-flask
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: spacemaker-python-flask-service
spec:
  selector:
    app: spacemaker-python-flask-pod
  ports:
  - protocol: TCP
    port: 5000