---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemaker-rust-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemaker-rust-pod
  template:
    metadata:
      labels:
        app: spacemaker-rust-pod
    spec:
      containers:
      - name: spacemaker-rust-container
        image: havardh/spacemaker-rust
        ports:
        - containerPort: 3003
---
kind: Service
apiVersion: v1
metadata:
  name: spacemaker-rust-service
spec:
  selector:
    app: spacemaker-rust-pod
  ports:
  - protocol: TCP
    port: 3003
  type: NodePort
