---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemaker-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemaker-rust
  template:
    metadata:
      labels:
        app: spacemaker-rust
    spec:
      containers:
      - name: spacemaker-rust
        image: havardh/spacemaker-rust
        ports:
        - containerPort: 3003
---
kind: Service
apiVersion: v1
metadata:
  name: spacemaker-rust
spec:
  selector:
    app: spacemaker-rust
  ports:
  - protocol: TCP
    port: 3003
  type: NodePort
